# Introduction to Pandas Lab

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

### 1. Import Numpy and Pandas and alias them to `np` and `pd` respectively.

In [1]:
import pandas as pd
import numpy as np

### 2. Create a Pandas Series containing the elements of the list below.

In [3]:
lst = [5.7, 75.2, 74.4, 84.0, 66.5, 66.3, 55.8, 75.7, 29.1, 43.7]

In [4]:
# your code here
data= pd.Series(lst)

### 3. Use indexing to return the third value in the Series above.

*Hint: Remember that indexing begins at 0.*

In [6]:
data[2]

74.4

### 4. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [7]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [123]:
df=pd.DataFrame(b)

### 5. Rename the data frame columns based on the names in the list below.

In [124]:
columns=['Score_1','Score_2','Score_3','Score_4','Score_5',]

In [125]:
# your code here

df.columns=columns
df

   Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 6. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [127]:
# your code here
d= df.iloc[:,[0, 2, 4]]

   Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 7. From the original data frame, calculate the average Score_3 value.

In [26]:
# your code here
df.Score_3.mean()

56.95000000000001

### 8. From the original data frame, calculate the maximum Score_4 value.

In [27]:
# your code here
df.Score_4.max()

88.8

### 9. From the original data frame, calculate the median Score 2 value.

In [28]:
# your code here
df.Score_2.median()

40.75

### 10. Create a Pandas DataFrame from the dictionary of product orders below.

In [29]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [32]:
# your code here
df2=pd.DataFrame(orders)

### 11. Calculate the total quantity ordered and revenue generated from these orders.

In [36]:
# your code here
x=df2.Quantity.sum()
y=df2.Revenue.sum()

2978

### 12. Obtain the prices of the most expensive and least expensive items ordered and print the difference.

In [41]:
# your code here
max_pr=df2.UnitPrice.max()
min_pr=df2.UnitPrice.min()

print(max_pr - min_pr)

11.77

## Let's load another dataset for more exercisesº

In [110]:
# Run this code:
admissions = pd.read_csv('/content/Admission_Predict.csv')

Let's evaluate the dataset by looking at the `head` function.

In [111]:
# your code here
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90

### 1 - Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [112]:
# your code here
admissions.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

###  2 -  Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [113]:
i=admissions['Serial No.']
admissions.set_index(i, drop=False, inplace=True)
admissions

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3.0,3.5,8.00,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.80
4,4,314,103,2,2.0,3.0,8.21,0,0.65
5,5,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
381,381,324,110,3,3.5,3.5,9.04,1,0.82
382,382,325,107,3,3.0,3.5,9.11,1,0.84
383,383,330,116,4,5.0,4.5,9.45,1,0.91
384,384,312,103,3,3.5,4.0,8.78,0,0.67
385,385,333,117,4,5.0,4.0,9.66,1,0.95

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

### 3 - In this part of the lab, we would like to test complex conditions on the entire data set at once. Let's start by finding the number of rows where the CGPA is greater than 9 and the student has performed an investigation.

In [116]:

column_names = admissions.columns

# Convert the list into a pandas DataFrame
admissions_df = pd.DataFrame(admissions, columns=column_names)

filtered_admissions = admissions_df[admissions_df["CGPA"] > 9]

filtered_admissions

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
5,5,330,115,5,4.5,3.0,9.34,1,0.90
11,11,328,112,4,4.0,4.5,9.10,1,0.78
20,20,328,116,5,5.0,5.0,9.50,1,0.94
21,21,334,119,5,5.0,4.5,9.70,1,0.95
...,...,...,...,...,...,...,...,...,...
380,380,329,111,4,4.5,4.0,9.23,1,0.89
381,381,324,110,3,3.5,3.5,9.04,1,0.82
382,382,325,107,3,3.0,3.5,9.11,1,0.84
383,383,330,116,4,5.0,4.5,9.45,1,0.91
385,385,333,117,4,5.0,4.0,9.66,1,0.95

### 4 - Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [118]:
# your code here
filtered_admissions[filtered_admissions['SOP']<3.5].mean()

Serial No.           166.600
GRE Score            328.000
TOEFL Score          112.800
University Rating      3.400
SOP                    3.000
LOR                    3.400
CGPA                   9.130
Research               0.800
Chance of Admit        0.802
dtype: float64